from __future__ import annotations

from utils.helpers import utc_now_iso


MOCK_NEWS = {
    "AAPL": [
        {
            "source": "Mock Global News",
            "title": "Apple suppliers signal stable iPhone demand into next quarter",
            "url": "https://example.com/apple-demand",
            "published_at": utc_now_iso(),
            "content": "Suppliers noted resilient iPhone demand and stable premium device orders.",
            "ticker": "AAPL",
            "company": "Apple",
            "source_type": "news",
        },
        {
            "source": "Mock Official Release",
            "title": "Apple expands AI features in enterprise rollout",
            "url": "https://example.com/apple-ai",
            "published_at": utc_now_iso(),
            "content": "The company announced wider enterprise AI availability and productivity features.",
            "ticker": "AAPL",
            "company": "Apple",
            "source_type": "official",
        },
    ],
    "TSLA": [
        {
            "source": "Mock Markets Daily",
            "title": "Tesla faces fresh margin pressure amid EV discounting",
            "url": "https://example.com/tesla-margin",
            "published_at": utc_now_iso(),
            "content": "Analysts warned that continued discounting may weigh on automotive gross margins.",
            "ticker": "TSLA",
            "company": "Tesla",
            "source_type": "news",
        },
        {
            "source": "Mock X Buzz",
            "title": "Tesla social sentiment mixed after production chatter",
            "url": "https://example.com/tesla-x",
            "published_at": utc_now_iso(),
            "content": "Posts were mixed, with concerns over margins but optimism on future product pipeline.",
            "ticker": "TSLA",
            "company": "Tesla",
            "source_type": "social",
        },
    ],
    "NVDA": [
        {
            "source": "Mock AI Wire",
            "title": "NVIDIA demand remains strong across hyperscalers",
            "url": "https://example.com/nvda-demand",
            "published_at": utc_now_iso(),
            "content": "Large cloud buyers continue to invest in accelerators and AI infrastructure.",
            "ticker": "NVDA",
            "company": "NVIDIA",
            "source_type": "news",
        }
    ],
    "TCS": [
        {
            "source": "Mock Business News",
            "title": "TCS reports strong Q4 IT services growth in emerging markets",
            "url": "https://example.com/tcs-growth",
            "published_at": utc_now_iso(),
            "content": "Tata Consultancy Services showed robust performance in digital transformation and cloud services.",
            "ticker": "TCS",
            "company": "Tata Consultancy Services",
            "source_type": "news",
        },
        {
            "source": "Mock Financial Times",
            "title": "TCS expands AI and automation offerings to European clients",
            "url": "https://example.com/tcs-ai",
            "published_at": utc_now_iso(),
            "content": "The company announced new AI-driven solutions for banking and healthcare sectors in Europe.",
            "ticker": "TCS",
            "company": "Tata Consultancy Services",
            "source_type": "official",
        },
        {
            "source": "Mock LinkedIn Pulse",
            "title": "TCS social sentiment positive after earnings beat",
            "url": "https://example.com/tcs-social",
            "published_at": utc_now_iso(),
            "content": "Industry professionals express optimism about TCS's digital transformation leadership.",
            "ticker": "TCS",
            "company": "Tata Consultancy Services",
            "source_type": "social",
        },
        {
            "source": "NSE India Press Release",
            "title": "TCS Announces Q4 FY2024 Results - Revenue Growth of 15.2%",
            "url": "https://www.nseindia.com/press-release/tcs-q4-results",
            "published_at": utc_now_iso(),
            "content": "Tata Consultancy Services reported strong Q4 results with 15.2% revenue growth and 18% increase in net profit.",
            "ticker": "TCS",
            "company": "Tata Consultancy Services",
            "source_type": "official",
        },
        {
            "source": "BSE India Press Release",
            "title": "TCS Press Conference: Digital Transformation Strategy Update",
            "url": "https://www.bseindia.com/press-release/tcs-conference",
            "published_at": utc_now_iso(),
            "content": "TCS CEO discusses AI and cloud strategies in quarterly press conference with analysts.",
            "ticker": "TCS",
            "company": "Tata Consultancy Services",
            "source_type": "conference",
        },
    ],
    "INFY": [
        {
            "source": "Mock Business News",
            "title": "Infosys reports strong Q4 performance with 20% order book growth",
            "url": "https://example.com/infy-growth",
            "published_at": utc_now_iso(),
            "content": "Infosys showed robust performance in cloud and digital services with significant order book expansion.",
            "ticker": "INFY",
            "company": "Infosys",
            "source_type": "news",
        },
        {
            "source": "Mock Financial Times",
            "title": "Infosys expands generative AI offerings for European clients",
            "url": "https://example.com/infy-ai",
            "published_at": utc_now_iso(),
            "content": "The company announced new AI-driven solutions for banking and manufacturing sectors.",
            "ticker": "INFY",
            "company": "Infosys",
            "source_type": "official",
        },
        {
            "source": "Mock LinkedIn Pulse",
            "title": "Infosys social sentiment bullish on AI expansion",
            "url": "https://example.com/infy-social",
            "published_at": utc_now_iso(),
            "content": "Industry experts positive about Infosys's AI and cloud transformation initiatives.",
            "ticker": "INFY",
            "company": "Infosys",
            "source_type": "social",
        },
        {
            "source": "NSE India Press Release",
            "title": "Infosys Q4 FY2024 Results: 22% YoY Growth in Digital Services",
            "url": "https://www.nseindia.com/press-release/infy-q4-results",
            "published_at": utc_now_iso(),
            "content": "Infosys reported 22% year-over-year growth in digital services revenue with strong margin expansion.",
            "ticker": "INFY",
            "company": "Infosys",
            "source_type": "official",
        },
        {
            "source": "BSE India Press Conference",
            "title": "Infosys Investor Conference: FY2025 Guidance and Strategy",
            "url": "https://www.bseindia.com/press-conference/infy-guidance",
            "published_at": utc_now_iso(),
            "content": "Infosys management discusses FY2025 outlook and strategic initiatives in investor conference.",
            "ticker": "INFY",
            "company": "Infosys",
            "source_type": "conference",
        },
    ],
}

MOCK_PRICES = {
    "AAPL": {
        "ticker": "AAPL",
        "price": 208.15,
        "prev_close": 205.92,
        "daily_return": 0.0108,
        "volume": 65400000,
        "avg_volume": 59000000,
        "volatility_20d": 0.019,
        "momentum_5d": 0.024,
    },
    "TSLA": {
        "ticker": "TSLA",
        "price": 163.80,
        "prev_close": 167.40,
        "daily_return": -0.0215,
        "volume": 112000000,
        "avg_volume": 95000000,
        "volatility_20d": 0.041,
        "momentum_5d": -0.038,
    },
    "NVDA": {
        "ticker": "NVDA",
        "price": 944.10,
        "prev_close": 931.55,
        "daily_return": 0.0135,
        "volume": 52000000,
        "avg_volume": 48000000,
        "volatility_20d": 0.032,
        "momentum_5d": 0.052,
    },
    "TCS": {
        "ticker": "TCS",
        "price": 4250.75,
        "prev_close": 4180.30,
        "daily_return": 0.0168,
        "volume": 2100000,
        "avg_volume": 1800000,
        "volatility_20d": 0.015,
        "momentum_5d": 0.028,
    },
}
